# Generated by Django 4.2.19 on 2025-02-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(upload_to='uploads/')),
                ('instance', models.CharField(max_length=255)),
                ('date_of_generation', models.DateTimeField(auto_now_add=True)),
                ('original_name', models.CharField(max_length=255)),
                ('extracted_data', models.JSONField()),
                ('uploader', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-date_of_generation'],
            },
        ),
    ]
