# Generated by Django 4.2.19 on 2025-02-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='extracted_data',
            field=models.JSONField(null=True),
        ),
    ]
